// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.5.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides ++= Seq(
  "com.beachape" % "enumeratum-macros_2.12" % "1.5.9",
  "com.beachape" % "enumeratum_2.12" % "1.5.13"
)
// LIBRARY_DEPENDENCIES_HASH 5e5a09804c046588bd048634f5478ad00852d80e
