// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.5.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides ++= Seq(
  "com.beachape" % "enumeratum-macros_2.12" % "1.5.9",
  "com.beachape" % "enumeratum_2.12" % "1.5.13"
)
// LIBRARY_DEPENDENCIES_HASH b0a03fd0ed70a0eba35b3a0a1e157fb1630b0a77
