// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.5.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides ++= Seq(
  "com.beachape" % "enumeratum-macros_2.12" % "1.5.9",
  "com.beachape" % "enumeratum_sjs0.6_2.12" % "1.5.13",
  "org.scala-js" % "scalajs-library_2.12" % "0.6.25"
)
// LIBRARY_DEPENDENCIES_HASH 579595ebbc8eff05b3ccbae732bf4fb72b7480da
