// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.5.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides ++= Seq(
  "com.beachape" % "enumeratum-macros_2.12" % "1.5.9",
  "com.beachape" % "enumeratum_sjs0.6_2.12" % "1.5.13",
  "org.scala-js" % "scalajs-library_2.12" % "0.6.24"
)
// LIBRARY_DEPENDENCIES_HASH cdc4f1092884ec1749a8c0ec0a149f0dacddc0bd
